# Generated by Django 5.2.4 on 2025-08-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Songs',
        ),
    ]
