# Generated by Django 5.2.4 on 2025-08-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room')], max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('name', 'room_type')},
            },
        ),
    ]
